language:
  - python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

before_script:
  - pip install coverage
  - pip install coveralls

script:
  - python tests.py
  - coverage run tests.py

after_sucess:
  - coveralls


notifications:
  email: false
